config/routes.rb
Rails.application.routes.draw do

  #append all controller methods to jobs route - example-> get 'jobs/index'
  resources :jobs

  root 'jobs#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  #before anything call the finjob method to find a job fro show, edit, update and destroy
  before_action :findJob, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank?
      @jobs = Job.all
    else
      @category_id = Category.find_by(name: params[:category]).id
      @jobs = Job.where(category_id: @category_id)
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(jobParams)

    if @job.save
      #add to db and redirect to that new job
      redirect_to @job
    else
      #render new page
      :new
    end
  end

  def update
    if @job.update(jobParams)
      redirect_to @job
    else
      :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to root_path
  end

  def show
  end

  def edit
  end

private
  def jobParams
    params.require(:job).permit(:title,:company,:about,:url,:category_id)
  end

  def findJob
    @job = Job.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/edit.html.erb
<h1>Jobs#edit</h1>

<%= form_for @job do |f| %>
    <%= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category" }%>
    <%= f.text_field :title, placeholder: "title" %>
    <%= f.text_field :company, placeholder: "company" %>
    <%= f.text_field :about, placeholder: "about" %>
    <%= f.text_field :url, placeholder: "url" %>

  <%= f.submit "submit"%>
<% end %>

<%= link_to "back home", root_path%>

app/views/jobs/index.html.erb
<h1>
    <% @jobs.each do |job| %>
        <h1><%= link_to job.title, job%></h1>
        <h3><%=job.company%></h3>
    <% end %>
</h1>

app/views/jobs/new.html.erb
<h1>Jobs#new</h1>
<%= form_for @job do |f| %>
    <%= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category" }%>
    <%= f.text_field :title, placeholder: "title" %>
    <%= f.text_field :company, placeholder: "company" %>
    <%= f.text_field :about, placeholder: "about" %>
    <%= f.text_field :url, placeholder: "url" %>

    <%= f.submit "submit"%>
<% end %>

<%= link_to "back home", root_path%>

app/views/jobs/show.html.erb
<h1>Jobs#show</h1>
<div>
    <h3><%=@job.title%></h3>
    <h3><%=@job.company%></h3>
    <h3><%=@job.about%></h3>
    <h3><%=@job.url%></h3>
</div>
<div>
    <%=link_to 'home', root_path%>
    <%=link_to 'edit', edit_job_path%>
    <%=link_to 'delete', job_path(@job), method: :delete, data: { confirm: "Are you sure you want to delete job?" }%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobbored</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'All jobs', root_path%>
    <% Category.all.each do |c| %>
        <%= link_to c.name, jobs_path(category: c.name)%>
    <%end%>
        <%= link_to 'add job', new_job_path%>
    <%= yield %>

  </body>
</html>